### ISSUE TITLE
Dropdown on web throwing error

### ISSUE THREAD

**Issue by sramac2** [crawlinknetworks/dropdown_plus#12]
As I start typing, it throws an error and says no match is found!
`The following _TypeError was thrown while processing the key message handler:
type 'bool' is not a subtype of type 'KeyEventResult'

When the exception was thrown, this was the stack:
#0      DropdownFormFieldState.build.<anonymous closure> (package:dropdown_plus/src/dropdown.dart:177:20)
#1      FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1593:32)
#2      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:832:37)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:389:35)
#6      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:386:46)
#7      _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#11     _invoke2 (dart:ui/hooks.dart:189:10)
#12     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#13     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#14     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#15     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
#16     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 3 frames from dart:async)

KeyMessage: KeyMessage([KeyDownEvent#70dca(physicalKey: PhysicalKeyboardKey#70004(usbHidUsage:
  "0x00070004", debugName: "Key A"), logicalKey: LogicalKeyboardKey#00061(keyId: "0x00000061",
  keyLabel: "A", debugName: "Key A"), character: "a", timeStamp: 14:06:21.689251)])
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: type 'bool' is not a subtype of type 'KeyEventResult'`

**Comment by acamenhas** [comment]
Same here

**Comment by florencemayo** [comment]
Hello! **any feedback on this matter?**


The following _TypeError was thrown while processing the key message handler:
type 'bool' is not a subtype of type 'KeyEventResult'

When the exception was thrown, this was the stack:
#0      DropdownFormFieldState.build.<anonymous closure> (package:dropdown_plus/src/dropdown.dart:177:20)
#1      FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1683:32)
#2      KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:824:34)
#3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:889:17)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#6      _invoke2 (dart:ui/hooks.dart:186:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:132:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)

KeyMessage: KeyMessage([KeyDownEvent#9947a(physicalKey: PhysicalKeyboardKey#700e0(usbHidUsage:
  "0x000700e0", debugName: "Control Left"), logicalKey: LogicalKeyboardKey#00100(keyId:
  "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), character: null, timeStamp:
  13:07:17.803494)])

**Comment by Fernandomr88** [comment]
Same issue here
