### ISSUE TITLE
How to use the onChanged function?

### ISSUE THREAD

**Issue by ShamanSharif** [crawlinknetworks/dropdown_plus#3]
`onChanged: (hi) => print("Hello"),`

this code gives a type error. 
error log:

> ======== Exception caught by gesture ===============================================================
> The following _TypeError was thrown while handling a gesture:
> type '(String) => void' is not a subtype of type '((dynamic) => void)?'
> 
> When the exception was thrown, this was the stack: 
> #0      DropdownFormFieldState._setValue (package:dropdown_plus/src/dropdown.dart:419:16)
> #1      DropdownFormFieldState._createOverlayEntry.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dropdown_plus/src/dropdown.dart:263:39)
> #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
> #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> #4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
> ...
> Handler: "onTap"
> Recognizer: TapGestureRecognizer#d43b3
>   debugOwner: GestureDetector
>   state: ready
>   won arena
>   finalPosition: Offset(172.3, 353.3)
>   finalLocalPosition: Offset(162.3, 12.7)
>   button: 1
>   sent tap down
> ====================================================================================================
>

**Comment by luca-colazzo** [comment]
Imagine being able to use one of the most important methods

**Comment by luca-colazzo** [comment]
fixed, PR sent

**Comment by luca-colazzo** [comment]
Bruh, you closed this but didn't accept the PR?

**Comment by ShamanSharif** [comment]
Wait brah, let me reopen this. I am sorry. I closed it by mistake

Shaman Sharif
________________________________
